import { describe, expect, it } from "vitest";
import { clearQuestionAnnotations, loadQuestionAnnotations, saveQuestionAnnotations, questionAnnotationStorageKey, validQuestionAnnotations, type QuestionAnnotation, type QuestionAnnotationContext, type QuestionAnnotationStorage } from "./question-annotations";

function memoryStorage(): QuestionAnnotationStorage { const values = new Map<string, string>(); return { getItem: (key) => values.get(key) ?? null, setItem: (key, value) => { values.set(key, value); }, removeItem: (key) => { values.delete(key); } }; }
const context: QuestionAnnotationContext = { surface: "read", resourceId: "test-t1", questionKey: "q-22" };
const marks: QuestionAnnotation[] = [{ id: "m1", target: "question", strokes: [{ points: [{ x: 0.1, y: 0.2 }, { x: 0.8, y: 0.21 }], color: "#e9b25d", width: 0.006 }] }, { id: "m2", target: "answer-A", strokes: [{ points: [{ x: 0.2, y: 0.5 }], color: "#2c78c5", width: 0.02 }] }];

describe("question annotation storage", () => {
  it("round-trips independent target ink and isolates scopes", () => { const storage = memoryStorage(); expect(saveQuestionAnnotations("user-1", context, marks, storage).status).toBe("saved"); expect(loadQuestionAnnotations("user-1", context, storage).state.marks).toEqual(marks); expect(loadQuestionAnnotations("user-2", context, storage).state.marks).toEqual([]); expect(loadQuestionAnnotations("user-1", { ...context, questionKey: "q-23" }, storage).state.marks).toEqual([]); });
  it("returns independent snapshots", () => { const storage = memoryStorage(); saveQuestionAnnotations("user-1", context, marks, storage); const loaded = loadQuestionAnnotations("user-1", context, storage); loaded.state.marks[0].strokes[0].points[0].x = 0.9; expect(loadQuestionAnnotations("user-1", context, storage).state.marks[0].strokes[0].points[0].x).toBe(0.1); });
  it("preserves malformed data until explicit deletion", () => { const storage = memoryStorage(); const key = questionAnnotationStorageKey("user-1", context); storage.setItem(key, "{broken"); expect(loadQuestionAnnotations("user-1", context, storage).status).toBe("corrupt"); expect(saveQuestionAnnotations("user-1", context, [], storage).status).toBe("unavailable"); expect(storage.getItem(key)).toBe("{broken"); expect(clearQuestionAnnotations("user-1", context, storage)).toBe(true); });
  it("rejects invalid geometry and duplicate target", () => { expect(validQuestionAnnotations([{ ...marks[0], strokes: [{ ...marks[0].strokes[0], width: NaN }] }])).toBe(false); expect(validQuestionAnnotations([{ ...marks[0], strokes: [{ ...marks[0].strokes[0], points: [{ x: -1, y: 0.5 }] }] }])).toBe(false); expect(validQuestionAnnotations([marks[0], { ...marks[0], id: "another" }])).toBe(false); });
  it("rejects oversized ink and storage failures", () => { const storage = memoryStorage(); saveQuestionAnnotations("user-1", context, marks, storage); expect(saveQuestionAnnotations("user-1", context, [{ ...marks[0], strokes: Array.from({ length: 301 }, () => marks[0].strokes[0]) }], storage).status).toBe("invalid"); const fail = () => { throw new Error("blocked"); }; expect(loadQuestionAnnotations("user-1", context, { getItem: fail, setItem: fail, removeItem: fail }).status).toBe("unavailable"); expect(clearQuestionAnnotations("user-1", context, { ...storage, removeItem: fail })).toBe(false); });
});
