"use client";

import { useEffect, useState } from "react";
import type { DictationLesson, DictationSegment } from "@/types/dictation";

const initialForm = { title: "", slug: "", sourceName: "", sourceType: "PARTNER_PERMISSION", sourceUrl: "", youtubeVideoId: "", thumbnailUrl: "", durationSeconds: "", level: "B2", topics: "SCIENCE_TECHNOLOGY", publicAttribution: "", transcriptOrigin: "RIGHTS_HOLDER_FILE", descriptionVi: "", licenseStatus: "PENDING", rightsEvidenceNote: "" };

export default function DictationAdminClient({ initialLessons }: { initialLessons: DictationLesson[] }) {
  const [lessons, setLessons] = useState(initialLessons);
  const [form, setForm] = useState(initialForm);
  const [selected, setSelected] = useState<DictationLesson | null>(initialLessons[0] ?? null);
  const [transcript, setTranscript] = useState("");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const [segments, setSegments] = useState<DictationSegment[]>([]);
  const set = (key: keyof typeof form, value: string) => setForm((state) => ({ ...state, [key]: value }));

  const selectedId = selected?.id;
  useEffect(() => {
    if (!selectedId) return;
    fetch(`/api/admin/dictation/lessons/${selectedId}`).then((response) => response.json()).then((body) => { if (body.success) setSegments(body.data.segments); }).catch(() => setSegments([]));
  }, [selectedId]);

  const create = async (event: React.FormEvent) => {
    event.preventDefault(); setBusy(true); setMessage("");
    try {
      const response = await fetch("/api/admin/dictation/lessons", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, thumbnailUrl: form.thumbnailUrl || null, descriptionVi: form.descriptionVi || null, durationSeconds: Number(form.durationSeconds), topics: form.topics.split(",").map((item) => item.trim()).filter(Boolean) }) });
      const body = await response.json();
      if (!body.success) throw new Error(body.error);
      setLessons((items) => [body.data, ...items]); setSelected(body.data); setMessage("Đã tạo bản nháp. Hãy nhập transcript.");
    } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể tạo bài học."); } finally { setBusy(false); }
  };
  const importTranscript = async () => {
    if (!selected) return; setBusy(true); setMessage("");
    try { const response = await fetch(`/api/admin/dictation/lessons/${selected.id}/import-transcript`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ transcript }) }); const body = await response.json(); if (!body.success) throw new Error(body.error); setLessons((items) => items.map((item) => item.id === selected.id ? { ...item, segmentCount: body.data.segmentCount } : item)); setSelected((item) => item ? { ...item, segmentCount: body.data.segmentCount } : item); setMessage(`Đã tạo ${body.data.segmentCount} đoạn. Kiểm tra transcript trước khi publish.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể nhập transcript."); } finally { setBusy(false); }
  };
  const publish = async () => {
    if (!selected) return; setBusy(true); setMessage("");
    try { const response = await fetch(`/api/admin/dictation/lessons/${selected.id}/publish`, { method: "POST" }); const body = await response.json(); if (!body.success) throw new Error(body.error); setLessons((items) => items.map((item) => item.id === selected.id ? body.data : item)); setSelected(body.data); setMessage("Đã publish bài nghe-chép."); } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể publish."); } finally { setBusy(false); }
  };
  const archive = async () => {
    if (!selected || !confirm("Archive bài này? Người học sẽ không còn thấy bài trong thư viện.")) return; setBusy(true); setMessage("");
    try { const response = await fetch(`/api/admin/dictation/lessons/${selected.id}/archive`, { method: "POST" }); const body = await response.json(); if (!body.success) throw new Error(body.error); setLessons((items) => items.map((item) => item.id === selected.id ? body.data : item)); setSelected(body.data); setMessage("Đã archive lesson."); } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể archive."); } finally { setBusy(false); }
  };
  const verifyRights = async () => {
    if (!selected) return; setBusy(true); setMessage("");
    try { const response = await fetch(`/api/admin/dictation/lessons/${selected.id}/verify-rights`, { method: "POST" }); const body = await response.json(); if (!body.success) throw new Error(body.error); setLessons((items) => items.map((item) => item.id === selected.id ? body.data : item)); setSelected(body.data); setMessage("Đã xác minh quyền sử dụng."); } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể xác minh quyền."); } finally { setBusy(false); }
  };

  return <div className="grid max-w-7xl gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="space-y-6"><form onSubmit={create} className="rounded-2xl border border-line bg-surface p-5"><div className="flex items-center justify-between"><h1 className="text-xl font-extrabold text-ink">Tạo lesson Nghe-chép</h1><span className="text-xs font-bold text-muted">Video phải có quyền sử dụng đã xác minh</span></div><div className="mt-5 grid gap-3 md:grid-cols-2"><Field label="Tiêu đề" value={form.title} onChange={(value) => set("title", value)} /><Field label="Slug (a-z, số, -)" value={form.slug} onChange={(value) => set("slug", value)} /><Field label="Tên nguồn" value={form.sourceName} onChange={(value) => set("sourceName", value)} /><Field label="YouTube video ID" value={form.youtubeVideoId} onChange={(value) => set("youtubeVideoId", value)} /><Field label="URL video gốc" value={form.sourceUrl} onChange={(value) => set("sourceUrl", value)} /><Field label="Thumbnail URL (tuỳ chọn)" value={form.thumbnailUrl} onChange={(value) => set("thumbnailUrl", value)} /><Field label="Thời lượng (giây)" value={form.durationSeconds} onChange={(value) => set("durationSeconds", value)} inputMode="numeric" /><Field label="Topics (ngăn cách bằng ,)" value={form.topics} onChange={(value) => set("topics", value)} /></div><div className="mt-3 grid gap-3 md:grid-cols-3"><Select label="Cấp độ" value={form.level} onChange={(value) => set("level", value)} values={["A2", "B1", "B2", "C1"]} /><Select label="Nguồn quyền" value={form.sourceType} onChange={(value) => set("sourceType", value)} values={["PARTNER_PERMISSION", "CC_BY", "PUBLIC_DOMAIN", "NC_LICENSE", "OTHER_LICENSE"]} /><Select label="Trạng thái quyền" value={form.licenseStatus} onChange={(value) => set("licenseStatus", value)} values={["PENDING", "VERIFIED", "EXPIRED"]} /></div><label className="mt-3 block text-sm font-bold text-ink">Attribution công khai<textarea value={form.publicAttribution} onChange={(event) => set("publicAttribution", event.target.value)} className="mt-1 w-full rounded-xl border border-line p-3 text-sm" rows={2} /></label><label className="mt-3 block text-sm font-bold text-ink">Mô tả tiếng Việt (tuỳ chọn)<textarea value={form.descriptionVi} onChange={(event) => set("descriptionVi", event.target.value)} className="mt-1 w-full rounded-xl border border-line p-3 text-sm" rows={2} /></label><label className="mt-3 block text-sm font-bold text-ink">Bằng chứng quyền sử dụng (chỉ admin thấy)<textarea value={form.rightsEvidenceNote} onChange={(event) => set("rightsEvidenceNote", event.target.value)} placeholder="Link/email xác nhận, ngày, phạm vi được phép..." className="mt-1 w-full rounded-xl border border-line p-3 text-sm" rows={2} /></label><button disabled={busy} className="mt-4 rounded-xl bg-accent px-5 py-2.5 text-sm font-extrabold text-white disabled:opacity-50">Tạo bản nháp</button></form>
    {selected && <section className="rounded-2xl border border-line bg-surface p-5"><h2 className="text-lg font-extrabold text-ink">2. Import transcript: {selected.title}</h2><p className="mt-1 text-sm text-muted">Dán nội dung SRT hoặc VTT đã được phép dùng. Nhập lại transcript sẽ thay toàn bộ segment của bản nháp.</p><textarea value={transcript} onChange={(event) => setTranscript(event.target.value)} placeholder="WEBVTT&#10;&#10;00:00:01.000 --> 00:00:05.000&#10;Transcript..." className="mt-4 min-h-52 w-full rounded-xl border border-line p-3 font-mono text-xs" /><div className="mt-3 flex flex-wrap gap-3"><button type="button" disabled={busy || !transcript.trim()} onClick={importTranscript} className="rounded-xl border border-accent px-4 py-2 text-sm font-extrabold text-accent disabled:opacity-50">Tạo segment</button>{selected.licenseStatus !== "VERIFIED" && <button type="button" disabled={busy} onClick={verifyRights} className="rounded-xl border border-amber-400 px-4 py-2 text-sm font-extrabold text-amber-800 disabled:opacity-50">Xác minh quyền</button>}<button type="button" disabled={busy || selected.segmentCount === 0 || selected.licenseStatus !== "VERIFIED"} onClick={publish} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-extrabold text-white disabled:opacity-50">Publish</button>{selected.status === "PUBLISHED" && <button type="button" disabled={busy} onClick={archive} className="rounded-xl border border-red-300 px-4 py-2 text-sm font-extrabold text-red-700 disabled:opacity-50">Archive</button>}</div></section>}
    {selected && segments.length > 0 && <section className="rounded-2xl border border-line bg-surface p-5"><h2 className="text-lg font-extrabold text-ink">3. Preview và chỉnh segment</h2><iframe title="Video preview" className="mt-4 aspect-video w-full rounded-xl" src={`https://www.youtube-nocookie.com/embed/${selected.youtubeVideoId}?rel=0`} allowFullScreen /><div className="mt-4 space-y-3">{segments.map((segment) => <SegmentEditor key={segment.id} lessonId={selected.id} segment={segment} disabled={selected.status === "PUBLISHED"} onSaved={(next) => setSegments((items) => items.map((item) => item.id === next.id ? next : item))} />)}</div></section>}
    {message && <p className="rounded-xl bg-sky-50 p-4 text-sm font-semibold text-sky-800">{message}</p>}</section>
    <aside className="rounded-2xl border border-line bg-surface p-4"><h2 className="font-extrabold text-ink">Lessons ({lessons.length})</h2><div className="mt-3 space-y-2">{lessons.map((lesson) => <button type="button" key={lesson.id} onClick={() => setSelected(lesson)} className={`w-full rounded-xl border p-3 text-left ${selected?.id === lesson.id ? "border-accent bg-accent/5" : "border-line hover:bg-surface-soft"}`}><p className="line-clamp-2 text-sm font-extrabold text-ink">{lesson.title}</p><p className="mt-1 text-xs font-semibold text-muted">{lesson.status} · {lesson.level} · {lesson.segmentCount} đoạn</p></button>)}</div></aside></div>;
}

function Field({ label, value, onChange, inputMode }: { label: string; value: string; onChange: (value: string) => void; inputMode?: React.HTMLAttributes<HTMLInputElement>["inputMode"] }) { return <label className="text-sm font-bold text-ink">{label}<input value={value} onChange={(event) => onChange(event.target.value)} inputMode={inputMode} className="mt-1 h-10 w-full rounded-xl border border-line px-3 text-sm font-normal" /></label>; }
function Select({ label, value, onChange, values }: { label: string; value: string; onChange: (value: string) => void; values: string[] }) { return <label className="text-sm font-bold text-ink">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 h-10 w-full rounded-xl border border-line bg-white px-3 text-sm font-normal">{values.map((item) => <option key={item}>{item}</option>)}</select></label>; }

function SegmentEditor({ lessonId, segment, disabled, onSaved }: { lessonId: string; segment: DictationSegment; disabled: boolean; onSaved: (segment: DictationSegment) => void }) {
  const [draft, setDraft] = useState({ startSeconds: String(segment.startSeconds), endSeconds: String(segment.endSeconds), speaker: segment.speaker ?? "", expectedText: segment.expectedText, accepted: segment.acceptedNormalizedAnswers.join("\n") });
  const [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); try { const response = await fetch(`/api/admin/dictation/lessons/${lessonId}/segments/${segment.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ startSeconds: Number(draft.startSeconds), endSeconds: Number(draft.endSeconds), speaker: draft.speaker || null, expectedText: draft.expectedText, acceptedNormalizedAnswers: draft.accepted.split("\n").map((item) => item.trim()).filter(Boolean) }) }); const body = await response.json(); if (body.success) onSaved(body.data); } finally { setSaving(false); } };
  return <article className="rounded-xl border border-line p-3"><div className="grid gap-2 sm:grid-cols-[70px_1fr_1fr]"><b className="pt-2 text-sm text-ink">#{segment.index}</b><input disabled={disabled} value={draft.startSeconds} onChange={(event) => setDraft((value) => ({ ...value, startSeconds: event.target.value }))} className="rounded-lg border border-line px-2 py-1 text-sm" aria-label="Start seconds" /><input disabled={disabled} value={draft.endSeconds} onChange={(event) => setDraft((value) => ({ ...value, endSeconds: event.target.value }))} className="rounded-lg border border-line px-2 py-1 text-sm" aria-label="End seconds" /></div><input disabled={disabled} value={draft.speaker} onChange={(event) => setDraft((value) => ({ ...value, speaker: event.target.value }))} placeholder="Speaker (tuỳ chọn)" className="mt-2 w-full rounded-lg border border-line px-2 py-1 text-sm" /><textarea disabled={disabled} value={draft.expectedText} onChange={(event) => setDraft((value) => ({ ...value, expectedText: event.target.value }))} className="mt-2 w-full rounded-lg border border-line p-2 text-sm" rows={2} /><textarea disabled={disabled} value={draft.accepted} onChange={(event) => setDraft((value) => ({ ...value, accepted: event.target.value }))} placeholder="Đáp án thay thế, mỗi dòng một câu" className="mt-2 w-full rounded-lg border border-line p-2 text-xs" rows={2} />{!disabled && <button type="button" disabled={saving} onClick={save} className="mt-2 rounded-lg border border-accent px-3 py-1.5 text-xs font-bold text-accent">{saving ? "Đang lưu" : "Lưu segment"}</button>}</article>;
}
