import styles from "./dashboard.module.css";
import { DashboardIcon, StudyCompanion } from "./DashboardArt";

function Block({ className = "" }: { className?: string }) { return <span aria-hidden="true" className={`${styles.skeletonBlock} ${className}`} />; }

export default function DashboardLoading() {
  return <main aria-busy="true" className={`${styles.dashboard} ${styles.page} flex-1 overflow-y-auto`}><p role="status" className="sr-only">Đang tải Trang chủ…</p><div className={styles.container}>
    <section aria-hidden="true" className={styles.hero}><div className={styles.heroCopy}><span className={styles.eyebrow}>✦ ENGLISHGO CÙNG BẠN</span><h1><span className={styles.heroName}>Chào bạn,</span>luyện tiếp thôi!</h1><p>Mỗi ngày một chút, tiến gần hơn đến điểm số bạn mong muốn.</p></div><div className={styles.companion}><StudyCompanion /></div><div className={styles.speech}><span>Cùng học thêm một chút hôm nay nhé!</span><span className={styles.speechAction}>Tiếp tục học <DashboardIcon name="arrow" /></span></div></section>
    <section aria-hidden="true" className={styles.overview}>{["Điểm số của bạn", "Điểm còn thiếu", "Số ngày đến ngày thi", "Động lực học"].map(label => <div key={label} className={styles.overviewCard}><h2>{label}</h2><Block className={styles.skeletonOverview} /></div>)}</section>
    <section aria-hidden="true"><div className={styles.periods}>{["Hôm nay", "Tuần", "Tháng", "Tất cả", "Tùy chỉnh"].map(label => <button tabIndex={-1} disabled key={label}>{label}</button>)}</div><div className={styles.rangeStatus}>Đang tải thống kê…</div><div className={styles.statsGrid}>{["Thời gian học", "Luyện đề", "Đọc", "Nghe", "Nói", "Viết", "Từ vựng", "Video"].map(label => <div key={label} className={styles.statCard}><span className={styles.iconTile} /><div className={styles.statCopy}><h3>{label}</h3><span className={styles.numberSkeleton} /><p>Đang tải…</p></div></div>)}</div></section>
    <section aria-hidden="true" className={styles.goals}><div className={styles.goalsSummary}><span className={styles.eyebrow}>TỪNG BƯỚC MỖI NGÀY</span><h2>Mục tiêu hôm nay</h2><p>Những bước nhỏ tạo nên kết quả lớn.</p><div className={styles.goalCount}><strong>—<span>/5</span></strong><span>mục tiêu hoàn thành</span></div><div className={styles.miniRings}>{["Đọc", "Nghe", "Từ vựng", "Luyện đề", "Video"].map(label => <div key={label}><div className={styles.ring}><svg viewBox="0 0 120 120"><circle className={styles.ringTrack} cx="60" cy="60" r="52" /></svg></div><span>{label}</span></div>)}</div></div><div className={styles.goalsDetail}><h3>Hôm nay bạn sẽ…</h3><div className={styles.goalRows}>{["Đọc", "Nghe", "Từ vựng", "Luyện đề", "Video"].map(label => <div key={label} className={styles.goalRow}><span className={styles.goalIcon}><Block /></span><div><div className={styles.goalRowHeading}><strong>{label}</strong><span>—</span></div><div className={styles.progressTrack} /></div></div>)}</div><button className={styles.settingsButton} disabled tabIndex={-1}>Cài đặt mục tiêu hằng ngày</button></div></section>
  </div></main>;
}
